AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'

Metrics/LineLength:
  Max: 300

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 300
